name: Build release presets

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

# env:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-11
        compilers:
          - llvm
        presets:
          - unixlike-clang-release
    
    steps:
    - uses: actions/checkout@v3

    - name: setup_cpp
      uses: aminya/setup-cpp@v1
      with:
        cmake: true
        ninja: true
        cppcheck: true
        compiler: ${{matrix.compilers}}

    - name: cmake_configure
      run: cmake --preset "${{matrix.presets}}"
      
    - name: cmake_build
      run: cmake --build ${{github.workspace}}/out/build/${{matrix.presets}}/
      
